sources:
    - https://github.com/diamondburned/gtkcord3
image: golang/1.14.1-buster
packages:
    - build-essential
    - pkg-config
    - libhandy-0.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgdk-pixbuf2.0-dev
tasks:
    - build: |
        go build -v .
